package com.mimosa.deeppokemon.entity;

/**
 * @program: deep-pokemon
 * @description: 宝可梦分类标签
 * @author: mimosa
 * @create: 2020//10//18
 */
public enum  Tag {
    //攻受标签
    STAFF("STAFF"),BALANCE("BALANCE"),BALANCE_ATTACK("BALANCE_ATTACK"),BALANCE_STAFF("BALANCE_STAFF"),
    ATTACK("ATTACK"),

    //使用率标签
    USELESS("USELESS"),POPULAR("POPULAR"),COMMON("COMMON"),

    //种族标签

    PRETTY_ATTACKSTATS("PRETTY_ATTACKSTATS"),EXCELLENT_ATTACKSTATS("EXCELLENT_ATTACKSTATS"),
    GOOD_ATTACKSTATS("GOOD_ATTACKSTATS"), NORMAL_ATTACKSTATS("NORMAL_ATTACKSTATS"),
    BAD_ATTACKSTATSS("BAD_ATTACKSTATS"),

    PRETTY_DEFENCESTATS("PRETTY_DEFENCESTATS"),EXCELLENT_DEFENCESTATS("EXCELLENT_DEFENCESTATS"),
    GOOD_DEFENCESTATS("GOOD_DEFENCESTATS"), NORMAL_DEFENCESTATS("NORMAL_DEFENCESTATS"),
    BAD_DEFENCESTATS("BAD_DEFENCESTATS"),

    PRETTY_SPASTATS("PRETTY_SPASTATS"),EXCELLENT_SPASTATS("EXCELLENT_SPASTATS"),GOOD_SPASTATS("GOOD_SPASTATS"),
    NORMAL_SPASTATS("NORMAL_SPASTATS"),BAD_SPASTATS("BAD_SPASTATS"),

    PRETTY_SPDSTATS("PRETTY_SPDSTATS"),EXCELLENT_SPDSTATS("EXCELLENT_SPDSTATS"),GOOD_SPDSTATS("GOOD_SPDSTATS"),
    NORMAL_SPDSTATS("NORMAL_SPDSTATS"),BAD_SPDSTATS("BAD_SPDSTATS"),

    PRETTY_SPESTATS("PRETTY_SPESTATS"),EXCELLENT_SPESTATS("EXCELLENT_SPESTATS"),GOOD_SPESTATS("GOOD_SPESTATS"),
    NORMAL_SPESTATS("NORMAL_SPESTATS"),BAD_SPESTATS("BAD_SPESTATS"),

    //属性标签
    TYPEDEFENSE("TYPEDEFENCE"),BASEDEFENSE("BASEDEFENSE"),


    DEFENCEABILITY("DEFENCEABILITY"),ATTACKABILITY("ATTACKABILITY");

    String name;

    private Tag(String tag) {
        this.name = tag;
    }

}
