spring:
    data:
        mongodb:
            uri: mongodb://mimosa:17471335qwe@localhost:27017/?authSource=admin
            database: deep_pokemon_test
    jackson:
        timeZone : GMT+8

server:
    port: 8080