server:
    port: 8080

spring:
    application:
        name: pokemon-portal
    profiles:
        active: develop
#        active: production,startCraw

eureka:
    client:
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/