server:
  port: 8761

spring:
  security:
    user:
      name: mimosa
      password: 0405@L1999

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/