spring:
  application:
    name: pokemon-crawler
  jackson:
    timeZone: GMT+8
  cloud:
    refresh:
      enabled: false
  profiles:
    active: develop
server:
  port: 8081

logging:
  level:
    com:
        netflix: ERROR