spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/deep_pokemon_dev_env?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      authentication-database: admin
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://mimosa:0405%40L1999@localhost:8761/eureka/
#logging:
#  level:
#   com:
#       mimosa:
#          deeppokemon:
#           crawler: DEBUG