spring:
  data:
    mongodb:
      authentication-database: admin
      database: deep_pokemon_test
      host: localhost
      port: 27017
      username: mimosa
      password: 17471335qwe
  jackson:
    timeZone : GMT+8
  profiles:
    active: startCraw
server:
  port: 8081
#logging:
#  level:
#   com:
#       mimosa:
#          deeppokemon:
#           crawler: DEBUG
