spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/?authSource=admin&serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      database: deep_pokemon_dev_env
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://mimosa:0405%40L1999@host.docker.internal:8761/eureka/
  instance:
    hostname: host.docker.internal