spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/deep_pokemon_dev_env?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
      authentication-database: admin
  jackson:
    timeZone : GMT+8
  profiles:
    active: startCraw
server:
  port: 8081
#logging:
#  level:
#   com:
#       mimosa:
#          deeppokemon:
#           crawler: DEBUG